name: Integration Tests Main

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master
    
env:
  SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/stock_price_db
  MYSQL_DATABASE: stock_price_db
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: default_mysql_pass
            
jobs:

  run-integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    
    steps:
    - name: Initialize MySQL
      run: sudo systemctl start mysql.service

    - name: Initialize first database
      run: |
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
        -u${{ env.SPRING_DATASOURCE_USERNAME }} -p${{ env.SPRING_DATASOURCE_PASSWORD }}

    - name: Boost user
      run: |
        mysql -e "ALTER USER '${{ env.SPRING_DATASOURCE_USERNAME }}'@'localhost' \
        IDENTIFIED WITH mysql_native_password BY 'root';" \
        -u${{ env.SPRING_DATASOURCE_USERNAME }} -p${{ env.SPRING_DATASOURCE_PASSWORD }}

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.9.3

    - name: compile and test to export
      run: |
        export SPRING_DATASOURCE_PASSWORD=root
        cd rest_api_service
        mvn clean package -Pprod
        
    - name: Rename the artifact
      run: cp rest_api_service/target/stockprice.jar stockprice-${{ github.sha }}.jar

    - name: Save the artifact
      uses: actions/upload-artifact@master
      with:
        name: rest_api_service
        path: stockprice-${{ github.sha }}.jar

  